### ISSUE TITLE
Get rid off all lint errors.

### ISSUE THREAD

**Issue by jureslak** [KrozekGimVic/Grafi#5]
Za preverjanje stila lahko uporabljate samo `./full_test.sh -s`.
Ko se vsak znebi svojega dela napak, naj napiše komentar, da bo zadnji lahko zaprl issue.

**Comment by jureslak** [comment]
Also get rid of all documentation warnings. `full_test.sh` should run without errors (at least on your part) before commiting.

**Comment by RokKos** [comment]
How to get rid of this error:
 `./test/topological_sort_bfs_test.cpp:4:  Found C++ system header after other header. Should be: topological_sort_bfs_test.h, c system, c++ system, other.  [build/include_order] [4]`. And is there really need for including vector and queue in your .cpp file if they are already specified in .hpp file. Because lint suggest that in this error: `
./src/topological_sort_bfs.cpp:17:  Add #include <queue> for queue<>  [build/include_what_you_use] [4]
./src/topological_sort_bfs.cpp:26:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]`

**Comment by jureslak** [comment]
the header order is wring. We are followind this header order: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes.
See commit 40334f6 for details. 

Well, that is a matter of style/safety. Sure they are not needed, while the header has the includes. But, it is good practice to include only the files you _really_ need in the header, and the rest in the cpp. So if someone was to remove the include from the header, it would cause trouble, it it was not in the cpp as well -- thats why you put it there as well, it makes things more independent. Of course, the other phososoph is, that whoever changed the header, must check and move the include to the cpp now. But we will stick to the style guide and include it there as well.

**Comment by RokKos** [comment]
Ooo thaks for explanation. Fixed in commit adc9e3fe283751f1144fee8fddea3804593d1f54. And also fixed all lint errors for my files.
